-- Staff Members table
CREATE TABLE IF NOT EXISTS staff_members (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  provider_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('accept_bids', 'manage_accounts', 'other')),
  custom_role_label TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_staff_members_provider ON staff_members(provider_id);
CREATE INDEX idx_staff_members_active ON staff_members(is_active);

COMMENT ON TABLE staff_members IS 'Staff members added by service providers to help manage their business';

-- RLS for staff_members (T1: provider owns their staff)
ALTER TABLE staff_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "providers_view_own_staff" ON staff_members
  FOR SELECT USING (auth.uid() = provider_id);

CREATE POLICY "providers_create_staff" ON staff_members
  FOR INSERT WITH CHECK (auth.uid() = provider_id);

CREATE POLICY "providers_update_own_staff" ON staff_members
  FOR UPDATE USING (auth.uid() = provider_id);

CREATE POLICY "providers_delete_own_staff" ON staff_members
  FOR DELETE USING (auth.uid() = provider_id);

-- Accounting Entries table
CREATE TABLE IF NOT EXISTS accounting_entries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  provider_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  entry_type TEXT NOT NULL CHECK (entry_type IN ('income', 'expense')),
  amount NUMERIC NOT NULL CHECK (amount > 0),
  gst_included BOOLEAN DEFAULT false,
  description TEXT NOT NULL,
  entry_date DATE NOT NULL,
  contract_id UUID REFERENCES contracts(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_accounting_entries_provider ON accounting_entries(provider_id);
CREATE INDEX idx_accounting_entries_date ON accounting_entries(entry_date DESC);
CREATE INDEX idx_accounting_entries_type ON accounting_entries(entry_type);

COMMENT ON TABLE accounting_entries IS 'Income and expense tracking for service providers';

-- RLS for accounting_entries (T1: provider owns their entries)
ALTER TABLE accounting_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "providers_view_own_entries" ON accounting_entries
  FOR SELECT USING (auth.uid() = provider_id);

CREATE POLICY "providers_create_entries" ON accounting_entries
  FOR INSERT WITH CHECK (auth.uid() = provider_id);

CREATE POLICY "providers_update_own_entries" ON accounting_entries
  FOR UPDATE USING (auth.uid() = provider_id);

CREATE POLICY "providers_delete_own_entries" ON accounting_entries
  FOR DELETE USING (auth.uid() = provider_id);

-- Invoices table
CREATE TABLE IF NOT EXISTS invoices (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  provider_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  contract_id UUID NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
  invoice_number TEXT NOT NULL,
  company_name TEXT NOT NULL,
  company_logo_url TEXT,
  issued_date DATE NOT NULL,
  custom_colors JSONB DEFAULT '{"primary": "#1B4FD8", "accent": "#06B6D4"}',
  sent_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(provider_id, invoice_number)
);

CREATE INDEX idx_invoices_provider ON invoices(provider_id);
CREATE INDEX idx_invoices_contract ON invoices(contract_id);
CREATE INDEX idx_invoices_date ON invoices(issued_date DESC);

COMMENT ON TABLE invoices IS 'Invoices generated by service providers for completed contracts';

-- RLS for invoices (T1: provider owns their invoices)
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "providers_view_own_invoices" ON invoices
  FOR SELECT USING (auth.uid() = provider_id);

CREATE POLICY "providers_create_invoices" ON invoices
  FOR INSERT WITH CHECK (auth.uid() = provider_id);

CREATE POLICY "providers_update_own_invoices" ON invoices
  FOR UPDATE USING (auth.uid() = provider_id);

CREATE POLICY "providers_delete_own_invoices" ON invoices
  FOR DELETE USING (auth.uid() = provider_id);

-- Allow clients to view invoices for their contracts
CREATE POLICY "clients_view_invoices" ON invoices
  FOR SELECT USING (
    auth.uid() IN (
      SELECT client_id FROM contracts WHERE contracts.id = invoices.contract_id
    )
  );

-- Subscription Plans table
CREATE TABLE IF NOT EXISTS subscription_plans (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  monthly_price NUMERIC(10,2) NOT NULL CHECK (monthly_price >= 0),
  feature_key TEXT NOT NULL UNIQUE,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_subscription_plans_active ON subscription_plans(is_active);

COMMENT ON TABLE subscription_plans IS 'Available subscription plans for service providers';

-- RLS for subscription_plans
ALTER TABLE subscription_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public_read_plans" ON subscription_plans
  FOR SELECT USING (is_active = true);

CREATE POLICY "admin_manage_plans" ON subscription_plans
  FOR ALL USING (
    auth.uid() IN (
      SELECT id FROM profiles WHERE email LIKE '%@bluetika.co.nz'
    )
  );

-- Provider Subscriptions table
CREATE TABLE IF NOT EXISTS provider_subscriptions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  provider_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  plan_id UUID NOT NULL REFERENCES subscription_plans(id) ON DELETE CASCADE,
  stripe_subscription_id TEXT UNIQUE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'cancelled')),
  billing_date INTEGER NOT NULL CHECK (billing_date >= 1 AND billing_date <= 28),
  grace_period_ends_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(provider_id, plan_id, status)
);

CREATE INDEX idx_provider_subscriptions_provider ON provider_subscriptions(provider_id);
CREATE INDEX idx_provider_subscriptions_status ON provider_subscriptions(status);
CREATE INDEX idx_provider_subscriptions_billing ON provider_subscriptions(billing_date);

COMMENT ON TABLE provider_subscriptions IS 'Active subscriptions for service providers';

-- RLS for provider_subscriptions (T1: provider views their own)
ALTER TABLE provider_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "providers_view_own_subscriptions" ON provider_subscriptions
  FOR SELECT USING (auth.uid() = provider_id);

CREATE POLICY "providers_create_subscriptions" ON provider_subscriptions
  FOR INSERT WITH CHECK (auth.uid() = provider_id);

CREATE POLICY "providers_update_own_subscriptions" ON provider_subscriptions
  FOR UPDATE USING (auth.uid() = provider_id);

CREATE POLICY "admin_manage_subscriptions" ON provider_subscriptions
  FOR ALL USING (
    auth.uid() IN (
      SELECT id FROM profiles WHERE email LIKE '%@bluetika.co.nz'
    )
  );

-- Seed default subscription plans
INSERT INTO subscription_plans (name, description, monthly_price, feature_key) VALUES
  ('Remove BlueTika Logo', 'Use your own email for sending and remove BlueTika branding', 5.00, 'remove_branding'),
  ('Email Hosting', 'Professional email hosting at name@yourcompany.co.nz', 5.00, 'email_hosting'),
  ('Custom Profile URL', 'Custom profile URL at bluetika.co.nz/yourname', 5.00, 'custom_url'),
  ('Additional Staff Member', 'Add staff members to help manage your business', 2.00, 'staff_member')
ON CONFLICT (feature_key) DO NOTHING;