ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS first_name TEXT,
ADD COLUMN IF NOT EXISTS last_name TEXT,
ADD COLUMN IF NOT EXISTS phone_number TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS city_region TEXT,
ADD COLUMN IF NOT EXISTS location TEXT,
ADD COLUMN IF NOT EXISTS bio TEXT,
ADD COLUMN IF NOT EXISTS is_client BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS is_provider BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS gst_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS driver_licence_verified BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS domestic_helper_verified BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS verification_status TEXT DEFAULT 'not_started';